openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
host:
paths:
  /getAllPilots:
    get:
      operationId: "getAllPilots"
      tags:
        - "Pilots"
      responses:
        200:
          description: A list of Pilots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pilot'
components:
  schemas:
    Pilot:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name



  
